<?php
namespace App\Http\Controllers;
use App\Models\PredictionPurchaseReminder;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;
class PredictionPurchaseReminderController extends Controller {
 public function store(Request $request,int $instrument): RedirectResponse {$v=$request->validate(['prediction_id'=>['required','integer'],'horizon_days'=>['required',Rule::in([5,10,15,20])],'intent'=>['required',Rule::in(['purchased','interested'])],'purchase_price'=>['required','numeric','gt:0'],'fixed_20d_exit_enabled'=>['nullable','boolean'],'dynamic_horizon_exit_enabled'=>['nullable','boolean'],'support_stop_enabled'=>['nullable','boolean'],'resistance_trailing_stop_enabled'=>['nullable','boolean']]);$prediction=DB::table('predictions')->where('id',$v['prediction_id'])->where('instrument_id',$instrument)->first();abort_unless($prediction,404);$rules=['fixed_20d'=>(bool)$request->boolean('fixed_20d_exit_enabled'),'dynamic_horizon'=>(bool)$request->boolean('dynamic_horizon_exit_enabled'),'support_stop'=>(bool)$request->boolean('support_stop_enabled'),'resistance_trailing_stop'=>(bool)$request->boolean('resistance_trailing_stop_enabled')];PredictionPurchaseReminder::updateOrCreate(['user_id'=>$request->user()->id,'prediction_id'=>$prediction->id,'horizon_days'=>$v['horizon_days']],['instrument_id'=>$instrument,'intent'=>$v['intent'],'purchase_price'=>$v['purchase_price'],'purchased_at'=>now(),'remind_on'=>now()->addDays((int)$v['horizon_days'])->toDateString(),'status'=>'active','notified_at'=>null,'exit_rules'=>$v['intent']==='purchased'?$rules:[],'exit_state'=>$v['intent']==='purchased'?'monitoring':'scheduled']);return back()->with('status',$v['intent']==='purchased'?__('Kaufauswertung und Exit-Überwachung wurden gespeichert.'):__('Kauferinnerung wurde gespeichert.')); }
 public function disable(Request $request, PredictionPurchaseReminder $reminder): RedirectResponse {abort_unless((int)$reminder->user_id===(int)$request->user()->id,404);$reminder->update(['status'=>'disabled']);return back()->with('status',__('Kauferinnerung wurde deaktiviert.'));}
 public function enable(Request $request, PredictionPurchaseReminder $reminder): RedirectResponse {abort_unless((int)$reminder->user_id===(int)$request->user()->id,404);$reminder->update(['status'=>'active','notified_at'=>null]);return back()->with('status',__('Kauferinnerung wurde aktiviert.'));}
 public function destroy(Request $request, PredictionPurchaseReminder $reminder): RedirectResponse {abort_unless((int)$reminder->user_id===(int)$request->user()->id,404);$reminder->delete();return back()->with('status',__('Kauferinnerung wurde gelöscht.'));}
}
