<x-app-layout>
    <div class="min-h-[calc(100dvh-90px)] py-4 text-[var(--ak-text)]" x-data="researchLab()">
        <header class="mb-4 flex flex-col gap-3 rounded-2xl border border-cyan-400/25 bg-[var(--ak-card)] p-5 shadow-[var(--ak-shadow)] lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-center gap-3"><div class="flex h-12 w-12 items-center justify-center rounded-2xl border border-cyan-300/30 bg-cyan-300/10 text-cyan-300"><x-heroicon-o-beaker class="h-6 w-6" /></div><div><p class="text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">{{ __('Research Lab · Pro') }}</p><h1 class="text-2xl font-black tracking-tight">{{ __('Modell-Labor') }}</h1><p class="mt-1 text-xs text-[var(--ak-muted)]">{{ __('Variiere Indikatoren und Makrodaten und vergleiche deine Modelle mit dem Standard.') }}</p></div></div>
            <div class="flex flex-wrap items-center gap-2"><span class="rounded-lg border border-amber-300/30 bg-amber-300/10 px-3 py-2 text-[11px] font-black text-amber-300">{{ number_format($universeCount, 0, ',', '.') }} / 5.000 {{ __('Aktien geladen') }}</span><a href="{{ route('dashboard') }}" class="inline-flex h-10 items-center gap-2 rounded-xl border border-[var(--ak-border)] bg-[var(--ak-card)] px-4 text-xs font-black text-[var(--ak-muted)] hover:text-cyan-300"><x-heroicon-o-arrow-left class="h-4 w-4" />{{ __('Dashboard') }}</a></div>
        </header>

        @if(session('status'))<div class="mb-4 rounded-xl border border-cyan-300/25 bg-cyan-300/10 px-4 py-3 text-xs font-bold text-cyan-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-4 rounded-xl border border-rose-300/25 bg-rose-300/10 px-4 py-3 text-xs font-bold text-rose-200">{{ $errors->first() }}</div>@endif
        @if($universeCount < 5000)<div class="mb-4 rounded-xl border border-amber-300/25 bg-amber-300/[.07] px-4 py-3 text-xs leading-5 text-amber-100"><strong class="text-amber-300">{{ __('Universum noch nicht vollständig importiert.') }}</strong> {{ __('Aktuell liegen :count aktive Aktien in der Datenbank. Für die geplante Liste der 5.000 größten Aktien muss der Universe-Import noch ausgeführt werden; die Research-Läufe können bereits mit der vorhandenen Auswahl getestet werden.', ['count' => number_format($universeCount, 0, ',', '.')]) }}</div>@endif

        <form method="POST" action="{{ route('setup.research-lab.start') }}" class="grid gap-4 xl:grid-cols-[.82fr_1.18fr]">@csrf
            <section class="ak-card p-4">
                <div class="mb-3 flex items-center justify-between"><div><p class="text-[10px] font-black uppercase tracking-[.16em] text-amber-300">{{ __('Universum') }}</p><h2 class="mt-1 text-lg font-black">{{ __('Bis zu 5.000 Aktien') }}</h2></div><span class="rounded-lg border border-cyan-300/25 bg-cyan-300/10 px-2 py-1 text-[10px] font-black text-cyan-300" x-text="selected.length + ' / 50 ausgewählt'"></span></div>
                <input type="search" x-model="search" placeholder="{{ __('Symbol oder Firmenname suchen …') }}" class="ak-input mb-2 h-10 w-full rounded-xl px-3 text-xs">
                <div class="max-h-[30rem] overflow-y-auto rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-2">
                    <template x-for="stock in filteredStocks" :key="stock.symbol"><label class="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-2 text-xs hover:bg-cyan-300/[.08]"><input type="checkbox" name="symbols[]" :value="stock.symbol" x-model="selected" :disabled="selected.length >= 50 && !selected.includes(stock.symbol)" class="h-4 w-4 rounded border-slate-600 bg-transparent text-cyan-400 focus:ring-cyan-400"><span class="font-black text-cyan-300" x-text="stock.symbol"></span><span class="min-w-0 truncate text-[var(--ak-muted)]" x-text="stock.name"></span><span class="ml-auto shrink-0 text-[10px] text-[var(--ak-muted)]" x-text="stock.country || '—'"></span></label></template>
                </div>
                <p class="mt-2 text-[10px] leading-4 text-[var(--ak-muted)]">{{ __('Die Rangliste wird nach Marktkapitalisierung geführt. Pro Experiment sind maximal 50 Aktien erlaubt; mehrere Experimente können nacheinander gestartet werden.') }}</p>
            </section>

            <section class="ak-card p-4">
                <div class="mb-3 flex items-center justify-between"><div><p class="text-[10px] font-black uppercase tracking-[.16em] text-amber-300">{{ __('Konfiguration') }}</p><h2 class="mt-1 text-lg font-black">{{ __('Triple-Timeline Regeln') }}</h2></div><span class="rounded-lg border border-emerald-300/25 bg-emerald-300/10 px-2 py-1 text-[10px] font-black text-emerald-300">{{ __('Exit-Timing automatisch') }}</span></div>
                <div class="grid gap-3 sm:grid-cols-2">
                    <label class="rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><span class="text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Historie') }}</span><select name="training_years" class="ak-input mt-2 h-9 w-full rounded-lg px-2 text-xs"><option value="30">30 {{ __('Jahre') }}</option><option value="20">20 {{ __('Jahre') }}</option><option value="10">10 {{ __('Jahre') }}</option></select></label>
                    <label class="rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><span class="text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Benchmark-Zuordnung') }}</span><select name="benchmark_mode" class="ak-input mt-2 h-9 w-full rounded-lg px-2 text-xs"><option value="auto">{{ __('Automatisch: Land/Exchange') }}</option><option value="index">{{ __('Enthaltener Index') }}</option><option value="exchange">{{ __('Exchange-Index') }}</option><option value="sector">{{ __('Sektor-Index') }}</option></select></label>
                    <label class="rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3 sm:col-span-2"><span class="text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Prognosehorizonte') }}</span><div class="mt-2 flex flex-wrap gap-2">@foreach([5,10,15,20] as $h)<label class="inline-flex items-center gap-2 rounded-lg border border-cyan-300/25 bg-cyan-300/[.07] px-3 py-2 text-xs font-black text-cyan-200"><input type="checkbox" name="horizons[]" value="{{ $h }}" checked class="h-4 w-4 rounded border-slate-600 bg-transparent text-cyan-400 focus:ring-cyan-400">{{ $h }}d</label>@endforeach</div></label>
                </div>
                <div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><span class="flex justify-between text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]"><span>{{ __('Trefferquote mindestens') }}</span><b class="text-cyan-300" x-text="hit + ' %'"></b></span><input name="minimum_hit_rate" type="range" min="0" max="100" step="1" x-model="hit" class="mt-3 w-full accent-cyan-400"></label><label class="rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><span class="flex justify-between text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]"><span>{{ __('Profitfaktor mindestens') }}</span><b class="text-amber-300" x-text="pf"></b></span><input name="minimum_profit_factor" type="range" min="0" max="10" step=".05" x-model="pf" class="mt-3 w-full accent-amber-400"></label><label class="rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><span class="text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Backtest-Trades mindestens') }}</span><input name="minimum_trades" type="number" min="1" max="10000" value="15" class="ak-input mt-2 h-9 w-full rounded-lg px-2 text-xs"></label><label class="rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><span class="text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Shadow-Test') }}</span><select name="shadow_days" class="ak-input mt-2 h-9 w-full rounded-lg px-2 text-xs"><option value="60">60 {{ __('Tage') }}</option><option value="20">20 {{ __('Tage') }}</option><option value="120">120 {{ __('Tage') }}</option></select></label></div>
                <div class="mt-3 rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><p class="text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Indikatoren mit variablen Zeiträumen') }}</p><p class="mt-1 text-[10px] text-[var(--ak-muted)]">{{ __('Mehrere Perioden kommasepariert angeben; die Pipeline testet jede Variante.') }}</p><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach(['SMA','EMA','RSI','ROC','MACD','Bollinger','ATR','ADX','Stochastic','CCI','MFI','VWAP','OBV','Williams %R','Momentum'] as $indicator)@php($indicatorKey = strtolower(str_replace(' ','_', $indicator)))<label class="flex items-center gap-2 rounded-lg border border-cyan-300/15 px-2 py-1.5 text-xs text-[var(--ak-muted)]"><input type="checkbox" name="indicators[]" value="{{ $indicatorKey }}" checked class="h-3.5 w-3.5 rounded border-slate-600 bg-transparent text-cyan-400 focus:ring-cyan-400"><span class="w-20 shrink-0 font-bold">{{ $indicator }}</span><input name="indicator_periods[{{ $indicatorKey }}]" value="5,10,14,20,50,100" class="ak-input h-7 min-w-0 flex-1 rounded-md px-2 text-[10px]" aria-label="{{ __('Perioden') }}"></label>@endforeach</div></div>
                <div class="mt-3 rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3"><p class="text-[10px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Makrodaten und Lags') }}</p><p class="mt-1 text-[10px] text-[var(--ak-muted)]">{{ __('Der Lag verhindert Look-ahead und kann je Quelle angepasst werden.') }}</p><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach(['US2Y','US10Y','AGG','S&P 500','Öl','Gold','EUR/USD','VDAX'] as $macro)<label class="flex items-center gap-2 rounded-lg border border-cyan-300/20 px-2 py-1.5 text-xs text-[var(--ak-muted)]"><input type="checkbox" name="macros[]" value="{{ $macro }}" checked class="h-3.5 w-3.5 rounded border-slate-600 bg-transparent text-cyan-400 focus:ring-cyan-400"><span class="flex-1 font-bold">{{ $macro }}</span><select name="macro_lags[{{ $macro }}]" class="ak-input h-7 w-24 rounded-md px-1 text-[10px]"><option value="0">0d</option><option value="1" selected>1d</option><option value="5">5d</option><option value="20">20d</option></select></label>@endforeach</div></div>
                <div class="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--ak-border)] pt-4"><p class="max-w-xl text-[10px] leading-4 text-[var(--ak-muted)]">{{ __('Standardablauf: Training für 5/10/15/20 Tage → Backtest → Walk-Forward-Test → Noise-Filter-Analyse. Der Noise Filter bewertet die signierte Fläche der vier Prognosekurven und wird erst nach dem Walk-Forward-Test angewendet.') }}</p><button type="submit" :disabled="selected.length===0" class="inline-flex h-11 items-center gap-2 rounded-xl border border-cyan-300/35 bg-cyan-400/15 px-5 text-xs font-black text-cyan-200 shadow-[0_8px_24px_rgba(34,211,238,.12)] disabled:cursor-not-allowed disabled:opacity-40"><x-heroicon-o-play class="h-4 w-4" />{{ __('Training & Tests starten') }}</button></div>
            </section>
        </form>

        <section class="mt-4 ak-card p-4"><div class="flex items-center justify-between"><div><p class="text-[10px] font-black uppercase tracking-[.16em] text-amber-300">{{ __('Experimente') }}</p><h2 class="mt-1 text-lg font-black">{{ __('Deine Research-Läufe') }}</h2></div><span class="text-[10px] text-[var(--ak-muted)]">{{ __('Ergebnisse werden pro Lauf versioniert') }}</span></div><div class="mt-3 grid gap-2 lg:grid-cols-3">@forelse($experiments as $experiment)<article class="research-experiment rounded-xl border border-[var(--ak-border)] bg-[var(--ak-surface-muted)] p-3" data-status-url="{{ route('setup.research-lab.status', $experiment) }}"><div class="flex items-center justify-between"><b class="text-xs font-black text-cyan-300">{{ \Illuminate\Support\Str::limit(implode(', ', $experiment->symbols), 34) }}</b><span data-progress class="rounded-md border border-cyan-300/20 px-2 py-1 text-[10px] font-black text-cyan-200">{{ $experiment->progress }}%</span></div><p data-state class="mt-2 text-[10px] text-[var(--ak-muted)]">{{ $experiment->created_at?->format('d.m.Y H:i') }} · {{ __($experiment->stage) }} · {{ __($experiment->status) }}</p><div class="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-700"><span data-bar class="block h-full rounded-full bg-cyan-400 transition-all" style="width: {{ $experiment->progress }}%"></span></div></article>@empty<div class="rounded-xl border border-dashed border-[var(--ak-border)] p-6 text-center text-xs text-[var(--ak-muted)] lg:col-span-3">{{ __('Noch keine Research-Läufe gestartet.') }}</div>@endforelse</div></section>
    </div>
    <script>
        function researchLab(){const stocks=@json($stocks->map(fn($s)=>['symbol'=>$s->symbol,'name'=>$s->name,'country'=>$s->country])->values());return{stocks,search:'',selected:[],hit:55,pf:1.3,get filteredStocks(){const q=this.search.toLowerCase().trim();return q?this.stocks.filter(s=>(s.symbol+' '+(s.name||'')).toLowerCase().includes(q)):this.stocks.slice(0,500)}}}
        document.addEventListener('DOMContentLoaded',()=>{const poll=async()=>{for(const card of document.querySelectorAll('.research-experiment')){try{const response=await fetch(card.dataset.statusUrl,{headers:{Accept:'application/json'}});if(!response.ok)continue;const data=await response.json();card.querySelector('[data-progress]').textContent=`${data.progress||0}%`;card.querySelector('[data-bar]').style.width=`${data.progress||0}%`;card.querySelector('[data-state]').textContent=`${data.stage||'—'} · ${data.status||'—'}`;}catch(error){/* transient polling errors are harmless */}}};poll();setInterval(poll,5000);});
    </script>
</x-app-layout>
