<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index,follow">
    <title>{{ $title }} · AktienKI</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        :root{color-scheme:dark;--bg:#06111f;--panel:#0b2031;--line:rgba(67,220,239,.22);--cyan:#55e7f3;--text:#e9f5f7;--muted:#94aeb5;--amber:#f6c94e}
        *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 82% 8%,rgba(55,215,232,.09),transparent 32%),linear-gradient(135deg,#06101d,#071526 62%,#08111e);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,sans-serif}
        a{color:inherit}.top{position:sticky;top:0;z-index:20;border-bottom:1px solid var(--line);background:rgba(3,14,23,.94);backdrop-filter:blur(18px)}.top-inner,.wrap{width:min(1120px,calc(100% - 32px));margin:auto}.top-inner{height:72px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:11px;text-decoration:none;font-weight:900;font-size:21px}.brand img{width:45px;height:45px;object-fit:contain}.brand b{color:var(--cyan)}.back{padding:10px 14px;border:1px solid var(--line);border-radius:11px;text-decoration:none;color:#c8e6e9;font-size:13px;font-weight:800}
        .wrap{padding:58px 0 80px}.eyebrow{color:var(--cyan);font-size:12px;font-weight:900;letter-spacing:.2em;text-transform:uppercase}.hero{padding:30px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(135deg,rgba(21,65,79,.38),rgba(9,26,41,.86));box-shadow:0 22px 70px rgba(0,0,0,.24)}h1{margin:9px 0 10px;font-size:clamp(34px,5vw,58px);letter-spacing:-.04em}.meta{color:var(--muted);font-size:13px}.notice{margin-top:20px;padding:14px 16px;border:1px solid rgba(246,201,78,.28);border-radius:13px;background:rgba(246,201,78,.07);color:#f9e6a0;font-size:13px;line-height:1.6}
        .legal{margin-top:22px;padding:clamp(22px,4vw,44px);border:1px solid var(--line);border-radius:24px;background:rgba(8,28,43,.9)}.legal h2{margin:34px 0 10px;font-size:21px;color:#f4fbfc}.legal h2:first-child{margin-top:0}.legal h3{margin:22px 0 8px;font-size:16px;color:#c9f8fb}.legal p,.legal li{color:#b5c8ce;line-height:1.75;font-size:14px}.legal ul,.legal ol{padding-left:22px}.legal strong{color:#eefbfc}.address{font-style:normal;line-height:1.75;color:#c8d9dd}.nav{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:22px}.nav a{padding:12px;border:1px solid var(--line);border-radius:11px;text-decoration:none;text-align:center;color:#a8c8ce;font-size:12px;font-weight:800}.nav a.active,.nav a:hover{border-color:rgba(85,231,243,.5);background:rgba(85,231,243,.08);color:#fff}@media(max-width:700px){.wrap{padding-top:28px}.hero,.legal{border-radius:17px}.nav{grid-template-columns:1fr 1fr}.top-inner{width:calc(100% - 22px)}.brand{font-size:17px}}
    </style>
</head>
<body>
@php
    $legal = config('legal');
    $missingCorporateDetails = blank($legal['register_court']) || blank($legal['register_number']);
    $pages = ['impressum'=>'Impressum','agb'=>'AGB','datenschutz'=>'Datenschutz','risikohinweise'=>'Risikohinweise','widerruf'=>'Widerruf','ki-transparenz'=>'KI-Transparenz'];
@endphp
<header class="top"><div class="top-inner"><a class="brand" href="{{ route('welcome') }}"><img src="{{ asset('brand/generated/bull-icon.png') }}" alt=""><span>aktien<b>KI</b>.com</span></a><a class="back" href="{{ url()->previous() === url()->current() ? route('welcome') : url()->previous() }}">← Zurück</a></div></header>
<main class="wrap">
    <section class="hero"><div class="eyebrow">Rechtliche Informationen</div><h1>{{ $title }}</h1><div class="meta">Version {{ $legal['legal_version'] }} · Stand {{ \Illuminate\Support\Carbon::parse($legal['effective_date'])->format('d.m.Y') }}</div>
        @if($missingCorporateDetails)<div class="notice"><strong>Vor Veröffentlichung vervollständigen:</strong> Registergericht, Handelsregisternummer und gegebenenfalls Gründungszusatz/USt‑IdNr. fehlen noch. Diese Fassung ist für Entwicklung und rechtliche Prüfung vorgesehen.</div>@endif
    </section>
    <nav class="nav" aria-label="Rechtliche Dokumente">@foreach($pages as $slug=>$label)<a class="{{ $document===$slug?'active':'' }}" href="{{ route('legal.show',$slug) }}">{{ $label }}</a>@endforeach</nav>
    <article class="legal">
        @if($document === 'impressum')
            <h2>Angaben gemäß § 5 DDG</h2><address class="address"><strong>{{ $legal['company'] }}</strong>@if($legal['formation_status']) {{ $legal['formation_status'] }}@endif<br>{{ $legal['street'] }}<br>{{ $legal['postal_code'] }} {{ $legal['city'] }}<br>{{ $legal['country'] }}</address>
            <h2>Vertretung und Kontakt</h2><p>Vertreten durch: <strong>{{ $legal['representative'] }}</strong><br>E‑Mail: <a href="mailto:{{ $legal['email'] }}">{{ $legal['email'] }}</a>@if($legal['phone'])<br>Telefon: {{ $legal['phone'] }}@endif</p>
            <h2>Registerangaben</h2><p>Registergericht: <strong>{{ $legal['register_court'] ?: '[vor Veröffentlichung ergänzen]' }}</strong><br>Registernummer: <strong>{{ $legal['register_number'] ?: '[vor Veröffentlichung ergänzen]' }}</strong>@if($legal['vat_id'])<br>Umsatzsteuer-Identifikationsnummer: {{ $legal['vat_id'] }}@endif</p>
            <h2>Verbraucherstreitbeilegung</h2><p>Wir sind nicht verpflichtet und derzeit nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen. Gesetzliche Informationspflichten nach Entstehen einer konkreten Streitigkeit bleiben unberührt.</p>
            <h2>Redaktionell Verantwortlicher</h2><p>Soweit erforderlich: {{ $legal['representative'] }}, Anschrift wie oben.</p>
        @elseif($document === 'agb')
            <h2>1. Geltungsbereich und Anbieter</h2><p>Diese AGB gelten für die Nutzung von AktienKI durch Verbraucher und Unternehmer. Anbieter ist {{ $legal['company'] }}, Anschrift wie im Impressum. Abweichende Bedingungen gelten nur nach ausdrücklicher Vereinbarung.</p>
            <h2>2. Leistungsgegenstand</h2><p>AktienKI stellt softwaregestützte Analyse-, Recherche-, Visualisierungs-, Simulations- und Benachrichtigungsfunktionen zu Wertpapieren bereit. Umfang, Limits und Speicherfunktionen richten sich nach dem gewählten Tarif. Die Inhalte sind allgemeine Informationen und keine persönliche Anlageberatung, Finanzportfolioverwaltung, Anlagevermittlung oder Garantie eines Anlageerfolgs.</p>
            <h2>3. Beta-Phase</h2><p>Während einer gekennzeichneten Beta können Funktionen unvollständig, vorübergehend nicht verfügbar oder fehlerhaft sein. Testdaten, Modelle, Tarife und Funktionsumfänge können angepasst werden. Produktive Anlageentscheidungen dürfen nicht allein auf Beta-Ausgaben gestützt werden. Soweit ein kostenloser Beta-Zugang zugesagt wird, ergibt sich dessen Dauer aus der individuellen Einladung.</p>
            <h2>4. Registrierung und Konto</h2><p>Nutzer müssen mindestens 18 Jahre alt und unbeschränkt geschäftsfähig sein, zutreffende Angaben machen und Zugangsdaten geheim halten. Automatisierte Mehrfachkonten, Account-Sharing, Umgehung von Tariflimits, Scraping sowie missbräuchliche oder rechtswidrige Nutzung sind untersagt.</p>
            <h2>5. Vertragsschluss, Laufzeit und Zahlung</h2><p>Ein kostenpflichtiger Vertrag kommt erst durch eindeutige Bestellung und Bestätigung zustande. Preise, Abrechnungszeitraum, Mindestlaufzeit und Kündigungsmöglichkeiten werden vor Bestellung angezeigt. Wiederkehrende Verträge können entsprechend der im Bestellprozess angegebenen Frist gekündigt werden; zwingende gesetzliche Kündigungsrechte bleiben bestehen.</p>
            <h2>6. Nutzungsrechte und Daten</h2><p>Die Software, Darstellung, Modelle, Auswertungslogik und bereitgestellten Inhalte sind geschützt. Nutzer erhalten ein einfaches, nicht übertragbares Recht zur vertragsgemäßen persönlichen Nutzung. Eine systematische Vervielfältigung, Weiterverbreitung, öffentliche Bereitstellung, Rückentwicklung oder Nutzung zum Aufbau konkurrierender Datensätze/Modelle ist untersagt, soweit nicht zwingendes Recht entgegensteht.</p>
            <h2>7. Nutzerinhalte</h2><p>An eigenen Eingaben behalten Nutzer ihre Rechte. Sie räumen dem Anbieter die zur Bereitstellung, Speicherung, Sicherung und Verarbeitung des Dienstes erforderlichen Rechte ein und gewährleisten, dass Eingaben keine Rechte Dritter oder Gesetze verletzen. Vertrauliche Informationen, Zugangsdaten und besondere Kategorien personenbezogener Daten sollen nicht in den KI-Chat eingegeben werden.</p>
            <h2>8. Verfügbarkeit und Änderungen</h2><p>Eine ununterbrochene Verfügbarkeit wird nicht geschuldet. Wartung, Sicherheitsmaßnahmen, Datenanbieter-Ausfälle und höhere Gewalt können die Nutzung einschränken. Wesentliche nachteilige Änderungen an laufenden Verbraucherverträgen erfolgen nur bei sachlichem Grund, in zumutbarem Umfang und mit gesetzlich erforderlicher Information/Kündigungsmöglichkeit.</p>
            <h2>9. Gewährleistung und Haftung</h2><p>Es gelten die gesetzlichen Mängelrechte. Unbeschränkt haften wir für Vorsatz, grobe Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit, nach Produkthaftungsrecht sowie im Umfang übernommener Garantien. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den vorhersehbaren, vertragstypischen Schaden begrenzt. Eine Haftung für Anlageverluste allein aufgrund marktbedingter Entwicklungen oder eigenverantwortlicher Nutzerentscheidungen besteht nicht; zwingende Haftung bleibt unberührt.</p>
            <h2>10. Sperrung und Beendigung</h2><p>Konten können bei Sicherheitsgefahr, Missbrauch oder erheblicher Vertragsverletzung angemessen gesperrt werden. Vor einer dauerhaften Sperrung wird grundsätzlich Gelegenheit zur Stellungnahme gegeben, sofern Sicherheits- oder Rechtsgründe nicht entgegenstehen.</p>
            <h2>11. Schlussbestimmungen</h2><p>Es gilt deutsches Recht unter Wahrung zwingender Verbraucherschutzvorschriften des Staates des gewöhnlichen Aufenthalts. Gerichtsstandsvereinbarungen gelten nur, soweit gesetzlich zulässig. Hinweise zur Verbraucherstreitbeilegung stehen im Impressum.</p>
        @elseif($document === 'risikohinweise')
            <h2>Keine Anlageberatung</h2><p>AktienKI liefert automatisiert erzeugte, allgemeine Analyse- und Informationsinhalte. Es findet keine Prüfung deiner persönlichen finanziellen Situation, Kenntnisse, Erfahrung, Verlusttragfähigkeit oder Anlageziele statt. Signale wie BUY, HOLD, WAIT oder SELL sind Modellklassen und keine persönliche Empfehlung oder Aufforderung zum Handel.</p>
            <h2>Kapitalverlustrisiko</h2><p>Wertpapiere unterliegen Kurs-, Markt-, Unternehmens-, Liquiditäts-, Währungs-, Zins-, Länder- und politischen Risiken. Verluste bis zum vollständigen Verlust des eingesetzten Kapitals sind möglich. Bei Hebelprodukten können Risiken darüber hinausgehen; AktienKI ist nicht für eine Beurteilung solcher Produkte bestimmt.</p>
            <h2>Modell- und Prognoserisiken</h2><ul><li>Prognosen sind Wahrscheinlichkeitsaussagen und können falsch sein.</li><li>Historische Performance, Backtests und Walk-Forward-Ergebnisse sind kein verlässlicher Indikator zukünftiger Ergebnisse.</li><li>Überanpassung, Datenfehler, Regimewechsel, geringe Stichproben und Survivorship-/Selection-Bias können Ergebnisse verzerren.</li><li>Confidence, Trefferquote, Profitfaktor, Drawdown, Stabilität und KI-Score messen nur definierte Modelleigenschaften und keine Sicherheit.</li><li>Ein bestandenes Quality Gate beseitigt Verlustrisiken nicht.</li></ul>
            <h2>Daten-, Kurs- und Ausführungsrisiken</h2><p>Kurse können verzögert, angepasst, unvollständig oder fehlerhaft sein. Angezeigte Preise sind nicht zwingend handelbare Ausführungskurse. Spreads, Slippage, Gebühren, Steuern, Handelsunterbrechungen, Währungsumrechnung und Liquidität können reale Ergebnisse deutlich verschlechtern.</p>
            <h2>Simulationen und Musterdepots</h2><p>Backtests und Musterdepots sind hypothetisch. Sie bilden reale Orderausführung, Marktimpact, Steuern und persönliche Einschränkungen möglicherweise nicht vollständig ab. Auch bei gleicher Strategie können reale Ergebnisse abweichen.</p>
            <h2>Eigenverantwortung</h2><p>Prüfe Daten und Annahmen anhand unabhängiger Quellen, diversifiziere angemessen und handle nur Risiken, die du verstehst und finanziell tragen kannst. Ziehe bei Bedarf zugelassene Finanz-, Steuer- oder Rechtsberatung hinzu.</p>
        @elseif($document === 'widerruf')
            <h2>Widerrufsrecht</h2><p>Verbraucher haben bei einem im Fernabsatz geschlossenen kostenpflichtigen Vertrag grundsätzlich das Recht, binnen vierzehn Tagen ohne Angabe von Gründen zu widerrufen. Die Frist beginnt mit Vertragsschluss.</p>
            <h2>Ausübung des Widerrufs</h2><p>Um das Widerrufsrecht auszuüben, musst du uns – {{ $legal['company'] }}, {{ $legal['street'] }}, {{ $legal['postal_code'] }} {{ $legal['city'] }}, E‑Mail <a href="mailto:{{ $legal['email'] }}">{{ $legal['email'] }}</a> – mittels einer eindeutigen Erklärung über deinen Entschluss informieren. Zur Fristwahrung genügt die rechtzeitige Absendung.</p>
            <h2>Folgen des Widerrufs</h2><p>Wir erstatten erhaltene Zahlungen unverzüglich und spätestens binnen vierzehn Tagen ab Eingang des Widerrufs. Wurde auf ausdrückliches Verlangen bereits während der Widerrufsfrist mit der Dienstleistung begonnen, kann für den bis zum Widerruf erbrachten Anteil Wertersatz anfallen, soweit die gesetzlichen Voraussetzungen erfüllt sind.</p>
            <h2>Muster-Widerrufsformular</h2><p>An {{ $legal['company'] }}, {{ $legal['street'] }}, {{ $legal['postal_code'] }} {{ $legal['city'] }}, {{ $legal['email'] }}:<br><br>Hiermit widerrufe ich den von mir abgeschlossenen Vertrag über die Nutzung von AktienKI.<br>Bestellt am: ______<br>Name: ______<br>Anschrift: ______<br>Datum/Unterschrift (nur bei Papier): ______</p>
            <p><strong>Hinweis:</strong> Ob und wann das Widerrufsrecht bei vollständig erbrachten digitalen Dienstleistungen erlischt, richtet sich nach den gesetzlichen Voraussetzungen und den im Bestellprozess eingeholten ausdrücklichen Erklärungen. Der bloße Bezug der Analysen zu Aktien lässt das Widerrufsrecht für ein Software-Abonnement nicht automatisch entfallen.</p>
        @elseif($document === 'ki-transparenz')
            <h2>Rolle der KI</h2><p>AktienKI verwendet statistische und Machine-Learning-Modelle zur Merkmalsextraktion, Prognose, Qualitätsbewertung und Zusammenfassung. Der AKI-Chat kann generative KI einsetzen. Modellberechnungen und generierte Texte können Fehler oder erfundene Zusammenhänge enthalten und ersetzen keine menschliche Prüfung.</p>
            <h2>Datenquellen und Aktualität</h2><p>Je nach Funktion werden lizenzierte oder öffentlich zugängliche Markt-, Unternehmens- und Makrodaten verarbeitet. Quelle, Börse, Währung, Zeitstempel und möglicher Verzögerungsstatus sollen in der jeweiligen Ansicht beachtet werden. Historische Trainingsdaten und angezeigte Chartdaten können aus unterschiedlichen, rechtlich zulässigen Quellen stammen.</p>
            <h2>Modellvalidierung</h2><p>Modelle können mit zeitlich getrennten Trainings-, Validierungs- und Testfenstern sowie Walk-Forward-Verfahren geprüft werden. Quality Gates sollen schwache Modelle aussortieren, garantieren aber weder Korrektheit noch positive Rendite.</p>
            <h2>Automatisierte Entscheidungen</h2><p>AktienKI trifft keine rechtsverbindlichen Entscheidungen über Nutzer und führt ohne gesonderte, ausdrückliche Integration keine Wertpapierorders aus. Nutzer entscheiden selbst, ob und wie sie Informationen verwenden.</p>
            <h2>Meldung problematischer Inhalte</h2><p>Fehlerhafte, irreführende oder rechtswidrige Inhalte können unter <a href="mailto:{{ $legal['email'] }}">{{ $legal['email'] }}</a> gemeldet werden. Bitte nenne Ansicht, Symbol, Zeitpunkt und eine kurze Fehlerbeschreibung.</p>
        @else
            <h2>1. Verantwortlicher</h2><p>{{ $legal['company'] }}, vertreten durch {{ $legal['representative'] }}, {{ $legal['street'] }}, {{ $legal['postal_code'] }} {{ $legal['city'] }}, E‑Mail <a href="mailto:{{ $legal['privacy_email'] }}">{{ $legal['privacy_email'] }}</a>.</p>
            <h2>2. Verarbeitete Daten und Zwecke</h2><ul><li><strong>Aufruf und Sicherheit:</strong> IP-Adresse, Zeit, URL, Browser-/Geräteinformationen und Protokolle zur Auslieferung, Fehleranalyse und Abwehr von Missbrauch.</li><li><strong>Konto und Vertrag:</strong> Name, E‑Mail, Passwort-Hash, Land/Region, Tarif, Einwilligungs- und Vertragsnachweise, Abrechnungs- und Supportdaten.</li><li><strong>Produktnutzung:</strong> Watchlists, Depots, Strategien, Labels, Filter, Einstellungen und Nutzungsereignisse zur Vertragserfüllung.</li><li><strong>KI-Chat:</strong> Eingaben, Kontext, Antworten, Token-/Kostenmetadaten und Sicherheitsprotokolle zur Beantwortung und Budgetsteuerung.</li><li><strong>Kommunikation:</strong> Nachrichten und Kontaktdaten zur Bearbeitung von Anfragen sowie – nur mit erforderlicher Einwilligung – Marketing.</li></ul>
            <h2>3. Rechtsgrundlagen</h2><p>Wir verarbeiten Daten insbesondere zur Vertragserfüllung und vorvertraglichen Durchführung (Art. 6 Abs. 1 lit. b DSGVO), zur Erfüllung rechtlicher Pflichten (lit. c), aufgrund berechtigter Interessen an sicherem und wirtschaftlichem Betrieb (lit. f) sowie aufgrund einer Einwilligung (lit. a). Einwilligungen können jederzeit mit Wirkung für die Zukunft widerrufen werden.</p>
            <h2>4. Empfänger und Auftragsverarbeiter</h2><p>Daten können an Hosting-, Datenbank-, E‑Mail-, Zahlungs-, Analyse-, Support- und KI-Dienstleister übermittelt werden, soweit dies erforderlich ist. Vor Produktivstart ist hier eine konkrete, geprüfte Liste aller eingesetzten Anbieter einschließlich Zweck, Sitz und Datenschutzlink aufzunehmen.</p>
            <h2>5. Drittlandübermittlungen</h2><p>Bei Empfängern außerhalb EU/EWR verwenden wir – soweit erforderlich – Angemessenheitsbeschlüsse, EU-Standardvertragsklauseln und ergänzende Schutzmaßnahmen. Details können unter der Datenschutzadresse angefordert werden.</p>
            <h2>6. Speicherdauer</h2><p>Wir speichern Daten nur so lange, wie es für den jeweiligen Zweck, Vertrag, Sicherheitsnachweis oder gesetzliche Aufbewahrungspflichten erforderlich ist. Kontodaten werden nach Vertragsende gelöscht oder eingeschränkt, soweit keine Pflichten oder Ansprüche entgegenstehen. Serverprotokolle und KI-Inhalte erhalten vor Produktivstart konkrete Löschfristen.</p>
            <h2>7. Cookies und lokale Speicherung</h2><p>Technisch erforderliche Cookies und lokale Speicherungen dienen Anmeldung, Sicherheit, Sprache, Theme und Sitzungsverwaltung. Nicht erforderliche Analyse- oder Marketingtechnologien werden nur nach wirksamer Einwilligung eingesetzt und müssen über eine Einwilligungsverwaltung widerrufbar sein.</p>
            <h2>8. Rechte betroffener Personen</h2><p>Dir stehen – soweit die Voraussetzungen vorliegen – Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und Widerruf erteilter Einwilligungen zu. Du kannst dich zudem bei einer Datenschutzaufsichtsbehörde beschweren.</p>
            <h2>9. Pflicht zur Bereitstellung</h2><p>Für Registrierung und Vertrag sind gekennzeichnete Pflichtangaben erforderlich. Ohne sie kann kein Konto oder Vertrag bereitgestellt werden. Freiwillige Angaben sind entsprechend gekennzeichnet.</p>
            <h2>10. Keine ausschließlich automatisierte Rechtsentscheidung</h2><p>Es findet keine ausschließlich automatisierte Entscheidung mit rechtlicher oder ähnlich erheblicher Wirkung im Sinne von Art. 22 DSGVO statt.</p>
            <h2>11. Sicherheit und Änderungen</h2><p>Wir setzen angemessene technische und organisatorische Maßnahmen ein. Diese Erklärung wird angepasst, wenn Funktionen, Anbieter oder Rechtslage sich ändern. Wesentliche Änderungen werden in geeigneter Form kenntlich gemacht.</p>
        @endif
    </article>
</main>
<x-cookie-consent />
</body>
</html>
