<x-app-layout>
    @php
        $qualityTone = match($stock->quality_class) {
            'quality' => 'border-emerald-400/45 text-emerald-400',
            'solid' => 'border-cyan-400/45 text-cyan-400',
            'basic' => 'border-amber-400/45 text-amber-400',
            'underperform' => 'border-rose-400/45 text-rose-400',
            default => 'border-slate-400/30 text-slate-400',
        };
        $latest = $stock->latest_prediction;
    @endphp
    <main class="ak-body min-h-[calc(100dvh-73px)] py-5 sm:py-8"><div class="ak-container">
        <a href="{{ request('return_to', route('predictions.index')) }}" class="mb-4 inline-flex items-center gap-2 text-xs font-bold text-[var(--ak-muted)] hover:text-cyan-400">← Zurück zur Tabelle</a>
        <header class="ak-card mb-4 border-cyan-400/25 p-5"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-[10px] font-black uppercase tracking-[.22em] text-cyan-500">Neue Remote-Datenbank · aktives Release</p><h1 class="mt-1 text-3xl font-black text-[var(--ak-text)]">{{ $stock->name ?: $stock->symbol }}</h1><p class="mt-2 text-sm text-[var(--ak-muted)]">{{ $stock->country_code }} · {{ $stock->exchange }} · {{ $stock->symbol }} · {{ $stock->currency }}@if($stock->sector_code) · {{ __($stock->sector_code) }}@endif</p></div><div class="flex flex-wrap gap-2"><span class="rounded-lg border px-3 py-2 text-xs font-black uppercase {{ $qualityTone }}">{{ $stock->quality_class }}</span><span class="rounded-lg border border-violet-400/35 px-3 py-2 text-xs font-black text-violet-400">{{ $stock->eligible_horizon_count }} freigegebene Horizonte</span></div></div></header>

        <div class="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
            <section class="ak-card overflow-hidden border-cyan-400/25 p-4" data-serving-chart data-url="{{ route('stocks.chart-data',['symbol'=>$stock->symbol]) }}"><div class="flex items-start justify-between gap-3"><div><p class="text-[9px] font-black uppercase tracking-[.16em] text-cyan-500">Live geladener Kurschart</p><h2 class="mt-1 text-lg font-black text-[var(--ak-text)]">Kursverlauf</h2></div><div class="text-right"><b data-chart-price class="block text-xl text-cyan-400">—</b><small data-chart-status class="text-[8px] uppercase text-[var(--ak-muted)]">wird geladen</small></div></div><svg class="mt-4 h-64 w-full rounded-xl border border-cyan-400/15 bg-cyan-400/[.025]" viewBox="0 0 1000 260" preserveAspectRatio="none" role="img" aria-label="Kursverlauf"><defs><linearGradient id="serving-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#22d3ee" stop-opacity=".28"/><stop offset="1" stop-color="#22d3ee" stop-opacity="0"/></linearGradient></defs><path data-chart-area fill="url(#serving-chart-fill)" d=""/><path data-chart-line fill="none" stroke="#22d3ee" stroke-width="3" vector-effect="non-scaling-stroke" d=""/></svg><p class="mt-2 text-[8px] text-[var(--ak-muted)]">Der Chart wird bei Seitenaufruf aus dem Kursanbieter-/Dateicache geladen; die Serving-Datenbank speichert keine Kurshistorie.</p></section>

            <section class="ak-card border-violet-400/25 p-4"><p class="text-[9px] font-black uppercase tracking-[.16em] text-violet-400">Letzte freigegebene Prediction</p>@if($latest)<div class="mt-4 flex items-end justify-between gap-3"><div><b class="text-3xl {{ $latest->signal==='BUY'?'text-emerald-400':($latest->signal==='SELL'?'text-rose-400':'text-amber-400') }}">{{ $latest->signal }}</b><small class="mt-1 block text-[9px] text-[var(--ak-muted)]">{{ $latest->horizon }}T · {{ \Illuminate\Support\Carbon::parse($latest->as_of)->format('d.m.Y H:i') }}</small></div><b class="text-2xl {{ (float)$latest->expected_return_percent>=0?'text-emerald-400':'text-rose-400' }}">{{ sprintf('%+.2f %%',$latest->expected_return_percent) }}</b></div><div class="mt-5 grid grid-cols-3 gap-2 text-center"><span class="rounded-lg border border-[var(--ak-border)] p-2"><small class="block text-[8px] uppercase text-[var(--ak-muted)]">Zielkurs</small><b>{{ is_numeric($latest->target_price)?number_format($latest->target_price,2,',','.').' '.$stock->currency:'—' }}</b></span><span class="rounded-lg border border-[var(--ak-border)] p-2"><small class="block text-[8px] uppercase text-[var(--ak-muted)]">Konfidenz</small><b>{{ is_numeric($latest->confidence_percent)?number_format($latest->confidence_percent,0,',','.').' %':'—' }}</b></span><span class="rounded-lg border border-[var(--ak-border)] p-2"><small class="block text-[8px] uppercase text-[var(--ak-muted)]">Risiko</small><b>{{ $latest->risk_score ?? '—' }}</b></span></div>@else<div class="mt-5 rounded-xl border border-amber-400/25 bg-amber-400/[.05] p-4"><b class="text-amber-400">Keine Prediction gespeichert</b><p class="mt-2 text-xs leading-5 text-[var(--ak-muted)]">Kein Horizont ist aktuell freigegeben oder der nächste Prediction-Lauf steht noch aus. Es wird bewusst keine ältere Prediction aus der bisherigen Datenbank angezeigt.</p></div>@endif<div class="mt-5 border-t border-[var(--ak-border)] pt-3 text-[9px] text-[var(--ak-muted)]"><p>Release: <span class="font-mono">{{ $stock->release_id }}</span></p><p class="mt-1">Pipeline {{ $stock->pipeline_version }} · {{ \Illuminate\Support\Carbon::parse($stock->released_at)->format('d.m.Y H:i') }}</p></div></section>
        </div>

        <section class="mt-4"><div class="mb-3"><p class="text-[9px] font-black uppercase tracking-[.16em] text-cyan-500">Champion-Auswahl je Horizont</p><h2 class="mt-1 text-xl font-black text-[var(--ak-text)]">Standard gegen TCN</h2></div><div class="grid gap-4 xl:grid-cols-3">@foreach([10,20,40] as $horizon)@php $scope=$stock->horizons->get($horizon); @endphp<article class="ak-card border-cyan-400/20 p-4">@if($scope)<div class="flex items-start justify-between"><div><b class="text-2xl text-cyan-400">{{ $horizon }}T</b><small class="block text-[8px] uppercase text-[var(--ak-muted)]">{{ $scope->quality_name }}</small></div><span class="rounded-md border px-2 py-1 text-[9px] font-black uppercase {{ $scope->variant==='pure_tcn'?'border-violet-400/40 text-violet-400':'border-cyan-400/40 text-cyan-400' }}">{{ $scope->variant_label }} Champion</span></div><div class="mt-4 grid grid-cols-2 gap-2">@foreach([['Standard',$scope->standard_metrics,'text-cyan-400'],['TCN',$scope->tcn_metrics,'text-violet-400']] as [$label,$metrics,$tone])<div class="rounded-xl border border-[var(--ak-border)] p-3"><b class="{{ $tone }}">{{ $label }}</b><dl class="mt-2 grid grid-cols-2 gap-x-2 gap-y-1 text-[9px]"><dt class="text-[var(--ak-muted)]">Trades</dt><dd class="text-right font-bold">{{ $metrics->trades }}</dd><dt class="text-[var(--ak-muted)]">Hitrate</dt><dd class="text-right font-bold">{{ is_numeric($metrics->hit_rate)?number_format($metrics->hit_rate,1,',','.').' %':'—' }}</dd><dt class="text-[var(--ak-muted)]">PF</dt><dd class="text-right font-bold">{{ is_numeric($metrics->profit_factor)?number_format($metrics->profit_factor,2,',','.'):'—' }}</dd><dt class="text-[var(--ak-muted)]">Ø Trade</dt><dd class="text-right font-bold {{ (float)($metrics->average_return??0)>=0?'text-emerald-400':'text-rose-400' }}">{{ is_numeric($metrics->average_return)?sprintf('%+.2f %%',$metrics->average_return):'—' }}</dd></dl></div>@endforeach</div><div class="mt-3 rounded-lg border px-3 py-2 {{ $scope->prediction_enabled?'border-emerald-400/30 bg-emerald-400/[.04]':'border-rose-400/25 bg-rose-400/[.04]' }}"><b class="text-[10px] {{ $scope->prediction_enabled?'text-emerald-400':'text-rose-400' }}">{{ $scope->prediction_enabled?'Prediction freigegeben':'Prediction gesperrt' }}</b><small class="mt-1 block text-[8px] leading-4 text-[var(--ak-muted)]">Einstiegsschwelle {{ is_numeric($scope->entry_threshold)?number_format($scope->entry_threshold*100,2,',','.').' %':'—' }} · {{ $scope->metrics->trades }} nicht überlappende OOS-Trades</small></div>@else<p class="text-sm text-[var(--ak-muted)]">Nicht trainiert.</p>@endif</article>@endforeach</div></section>

        <section class="ak-card mt-4 border-cyan-400/20 p-4"><p class="text-[9px] font-black uppercase tracking-[.16em] text-cyan-500">Fundamentaldaten · neue Datenbank</p><div class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-8">@foreach([['Marktkap.',$stock->market_cap,'currency'],['KGV',$stock->trailing_pe,'number'],['Forward-KGV',$stock->forward_pe,'number'],['Div.-Rendite',$stock->dividend_yield,'percent'],['Marge',$stock->profit_margin,'percent'],['Umsatzwachstum',$stock->revenue_growth,'percent'],['ROE',$stock->return_on_equity,'percent'],['Debt/Equity',$stock->debt_to_equity,'number']] as [$label,$value,$format])<div><small class="block text-[8px] font-black uppercase text-[var(--ak-muted)]">{{ $label }}</small><b class="mt-1 block">@if(!is_numeric($value))—@elseif($format==='percent'){{ number_format((float)$value*100,1,',','.') }} % @elseif($format==='currency'){{ number_format((float)$value/1000000000,1,',','.') }} Mrd. @else{{ number_format((float)$value,2,',','.') }}@endif</b></div>@endforeach</div><p class="mt-3 text-[8px] text-[var(--ak-muted)]">Snapshot {{ $stock->fundamental_snapshot_date ? \Illuminate\Support\Carbon::parse($stock->fundamental_snapshot_date)->format('d.m.Y') : '—' }}</p></section>
        <p class="mt-3 text-[9px] text-[var(--ak-muted)]">Modellquelle: aktienki_serving_next. Personenbezogene Daten werden auf dieser Seite nicht aus der Serving-Datenbank gelesen.</p>
    </div></main>
    <script>
        document.addEventListener('DOMContentLoaded', async () => {
            const root = document.querySelector('[data-serving-chart]'); if (!root) return;
            const status = root.querySelector('[data-chart-status]'), price = root.querySelector('[data-chart-price]');
            try {
                const response = await fetch(root.dataset.url, {headers:{Accept:'application/json'}}); if (!response.ok) throw new Error('HTTP '+response.status);
                const payload = await response.json(), candles = Array.isArray(payload.candles) ? payload.candles.slice(-252) : [];
                const values = candles.map(item => Number(item?.y?.[3])).filter(Number.isFinite); if (values.length < 2) throw new Error('Keine Kursdaten');
                const min=Math.min(...values), max=Math.max(...values), spread=Math.max(.000001,max-min), points=values.map((value,index)=>[index/(values.length-1)*1000,245-(value-min)/spread*225]);
                const line='M '+points.map(point=>point.map(value=>value.toFixed(2)).join(' ')).join(' L '), area=line+' L 1000 260 L 0 260 Z';
                root.querySelector('[data-chart-line]').setAttribute('d',line); root.querySelector('[data-chart-area]').setAttribute('d',area);
                price.textContent=new Intl.NumberFormat('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(values.at(-1))+' '+(payload.currency||''); status.textContent=(payload.source||'Kursquelle').replaceAll('_',' ');
            } catch (error) { status.textContent='derzeit nicht verfügbar'; }
        });
    </script>
</x-app-layout>
