<x-app-layout>
    <div class="flex h-[calc(100dvh-89px)] min-h-0 flex-col py-4 text-[var(--ak-text)]">
        <header class="mb-4 flex shrink-0 items-center justify-between gap-4">
            <div class="flex min-w-0 items-center gap-3">
                <div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-amber-300/25 bg-amber-300/[.08] text-amber-300"><x-heroicon-o-tag class="h-6 w-6" /></div>
                <div><p class="text-[10px] font-black uppercase tracking-[.16em] text-amber-400">{{ __('Setup · Plus') }}</p><h1 class="text-2xl font-black">{{ __('Label Manager') }}</h1><p class="mt-1 text-xs text-[var(--ak-muted)]">{{ __('Smart-Selection-Labels verwalten, aktivieren und Benachrichtigungen steuern.') }}</p></div>
            </div>
            <div class="flex items-center gap-2"><a href="{{ route('setup.quality') }}" class="inline-flex h-10 items-center gap-2 rounded-lg border border-amber-300/25 bg-amber-300/[.08] px-4 text-xs font-black text-amber-300 hover:bg-amber-300/[.15]"><x-heroicon-o-plus class="h-4 w-4" />{{ __('Neues Label') }}</a><a href="{{ route('dashboard') }}" class="inline-flex h-10 items-center gap-2 rounded-lg border border-[var(--ak-border)] px-4 text-xs font-black text-[var(--ak-muted)] hover:text-teal-400"><x-heroicon-o-arrow-left class="h-4 w-4" />{{ __('Dashboard') }}</a></div>
        </header>
        @if (session('status'))<div class="mb-3 rounded-xl border border-emerald-300/25 bg-emerald-400/[.08] px-4 py-3 text-xs font-bold text-emerald-300">{{ session('status') }}</div>@endif
        <section class="min-h-0 flex-1 overflow-y-auto rounded-2xl border border-[var(--ak-border)] bg-[color-mix(in_srgb,var(--ak-card)_58%,transparent)] p-3 shadow-[var(--ak-shadow)] backdrop-blur-xl">
            <div class="grid gap-3 xl:grid-cols-2">
                @forelse ($labels as $label)
                    @php $criteria = (array) $label->criteria; $icon = $label->icon ?: 'sparkles'; $iconComponent = 'heroicon-o-'.$icon; @endphp
                    <article class="rounded-xl border border-orange-300/25 bg-[color-mix(in_srgb,var(--ak-card)_58%,transparent)] p-4 shadow-[0_10px_28px_rgba(194,65,12,.08)]">
                        <form method="POST" action="{{ route('setup.labels.update', $label) }}" class="space-y-3">
                            @csrf @method('PATCH')
                            <div class="flex items-start gap-3"><div class="grid h-11 w-11 shrink-0 place-items-center rounded-xl border" style="border-color: {{ $label->color }}66; color: {{ $label->color }}; background: {{ $label->color }}18"><x-dynamic-component :component="$iconComponent" class="h-5 w-5" /></div><div class="min-w-0 flex-1"><input name="name" value="{{ $label->name }}" maxlength="80" required class="ak-input h-9 w-full rounded-lg px-3 text-sm font-black"><p class="mt-1 text-[9px] text-[var(--ak-muted)]">{{ __('Erstellt') }} {{ optional($label->created_at)->timezone('Europe/Berlin')->format('d.m.Y H:i') }}</p></div><label class="flex items-center gap-1.5 text-[9px] font-black uppercase text-[var(--ak-muted)]"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($label->is_active) class="h-4 w-4 rounded border-slate-500 bg-transparent text-teal-500">{{ __('Aktiv') }}</label></div>
                            <div class="grid grid-cols-[1fr_110px] gap-2"><label class="text-[9px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Symbol') }}<select name="icon" class="ak-input mt-1 h-9 w-full rounded-lg px-2 text-xs"><option value="sparkles" @selected($icon==='sparkles')>✨ {{ __('Favorit') }}</option><option value="bolt" @selected($icon==='bolt')>⚡ {{ __('Momentum') }}</option><option value="trophy" @selected($icon==='trophy')>🏆 {{ __('Top-Auswahl') }}</option><option value="shield-check" @selected($icon==='shield-check')>🛡 {{ __('Qualität') }}</option><option value="chart-bar" @selected($icon==='chart-bar')>▥ {{ __('Analyse') }}</option><option value="rocket-launch" @selected($icon==='rocket-launch')>🚀 {{ __('Chance') }}</option></select></label><label class="text-[9px] font-black uppercase tracking-wide text-[var(--ak-muted)]">{{ __('Farbe') }}<input name="color" type="color" value="{{ $label->color }}" class="mt-1 h-9 w-full cursor-pointer rounded-lg border border-[var(--ak-border)] bg-transparent p-1"></label></div>
                            <label class="flex cursor-pointer items-start gap-2 rounded-lg border border-cyan-300/15 bg-cyan-300/[.05] px-3 py-2 text-[10px] text-[var(--ak-muted)]"><input type="hidden" name="email_notification_enabled" value="0"><input type="checkbox" name="email_notification_enabled" value="1" @checked((bool) ($criteria['email_notification_enabled'] ?? false)) class="mt-0.5 h-4 w-4 rounded border-slate-500 bg-transparent text-teal-500"><span><strong class="block text-cyan-300">{{ __('E-Mail bei Kaufsignal') }}</strong>{{ __('Bei einem passenden neuen BUY-Signal benachrichtigen.') }}</span></label>
                            <div class="flex items-center justify-between gap-2 border-t border-[var(--ak-border)] pt-3"><span class="text-[9px] text-[var(--ak-muted)]">{{ __('Filterregeln bleiben dynamisch und werden monatlich retestet.') }}</span><div class="flex gap-2"><button type="submit" class="inline-flex h-8 items-center gap-1.5 rounded-lg bg-teal-500/15 px-3 text-[10px] font-black text-teal-300 hover:bg-teal-500/25"><x-heroicon-o-check class="h-3.5 w-3.5" />{{ __('Speichern') }}</button></form><form method="POST" action="{{ route('setup.labels.destroy', $label) }}" onsubmit="return confirm('{{ __('Label wirklich löschen?') }}')">@csrf @method('DELETE')<button type="submit" class="inline-flex h-8 items-center gap-1.5 rounded-lg border border-rose-300/20 px-3 text-[10px] font-black text-rose-300 hover:bg-rose-400/10"><x-heroicon-o-trash class="h-3.5 w-3.5" />{{ __('Löschen') }}</button></form></div></div>
                        </form>
                    </article>
                @empty
                    <div class="col-span-full flex min-h-56 flex-col items-center justify-center text-center"><x-heroicon-o-tag class="h-10 w-10 text-[var(--ak-muted)]" /><h2 class="mt-3 text-base font-black">{{ __('Noch keine Labels vorhanden') }}</h2><p class="mt-1 text-xs text-[var(--ak-muted)]">{{ __('Erstelle deine erste dynamische Smart Selection.') }}</p><a href="{{ route('setup.quality') }}" class="mt-4 rounded-lg bg-amber-400/15 px-4 py-2 text-xs font-black text-amber-300">{{ __('Smart Selection öffnen') }}</a></div>
                @endforelse
            </div>
        </section>
    </div>
</x-app-layout>
