<!doctype html><html lang="de"><head><meta charset="utf-8"><style>
@page{margin:9px 11px;background:#f3faf9}body{margin:0;background:#f3faf9;font-family:DejaVu Sans,sans-serif;color:#172033;font-size:6.5px;line-height:1.05}h1{font-size:13px;margin:0 0 1px;color:#0f3d46}h2{font-size:8.5px;margin:4px 0 2px;color:#0f3d46}.muted{color:#64748b;font-size:5.8px}.notice{margin:4px 0;padding:4px 6px;border:1px solid #e1b955;border-radius:4px;background:#fff8df;color:#684b0c;font-size:6px;font-weight:bold}.overview{width:100%;border-collapse:separate;border-spacing:3px;margin:3px -3px}.depot-card,.chart-card{height:104px;padding:6px;border:1px solid #9fd7d2;border-radius:5px;background:#f8fdfc;vertical-align:top}.depot-card h2,.chart-card h2{margin:0 0 5px;font-size:8px;text-transform:uppercase;letter-spacing:.4px;color:#0f766e}.depot-row{padding:2px 0;border-bottom:1px solid #d2e7e4}.depot-row span{color:#64748b}.depot-row b{float:right;color:#172033}.strategy{display:inline-block;margin:3px 2px 0 0;padding:2px 4px;border:1px solid #73aaa5;border-radius:3px;background:#dcebe7;color:#176c68;font-size:5.5px;font-weight:bold}.grid{width:100%;border-collapse:separate;border-spacing:2px;margin:3px -2px 2px}.card{background:#f8fdfc;border:1px solid #b8ddd9;border-radius:3px;padding:3px 3px;white-space:nowrap}.card b{font-size:5.2px;text-transform:uppercase;color:#64748b}.value{font-size:8px;font-weight:bold;margin-top:1px;color:#172033}table.data{width:100%;border-collapse:collapse;margin-top:1px;table-layout:fixed;background:#fbfefd}table.data th,table.data td{padding:1.4px 2.5px;border-bottom:.5px solid #d5e8e5;text-align:left;line-height:1.05}table.data th{background:#155e75;color:#ecfeff;font-size:5.3px;text-transform:uppercase}table.data tbody tr:nth-child(even){background:#eef8f6}table.data td:nth-child(1){width:11%}table.data td:nth-child(2){width:9%;font-weight:bold}table.data td:nth-child(3){width:12%;font-weight:bold}table.data td:nth-child(4){width:9%}table.data td:nth-child(5),table.data td:nth-child(6){width:11%}table.data td:last-child{font-size:5.7px}.buy{color:#087f78}.sell{color:#c2415d}
</style></head><body>
<h1>Depotsimulation · {{ $portfolio->name }}</h1><div class="muted">{{ $run->simulation_start_date }} – {{ $run->simulation_end_date }} · erstellt {{ now()->format('d.m.Y H:i') }}</div>
<div class="notice">Wichtiger Hinweis: Dieser Bericht zeigt ausschließlich eine Simulation auf historischen Daten. Vergangene Ergebnisse sind keine Garantie für zukünftige Entwicklungen und stellen keine Anlageberatung dar.</div>
@php
    $reportCurve = collect($summary['equity_curve'] ?? [])->filter(fn ($point) => isset($point['date'], $point['equity']))->values();
    $chartWidth = 560;
    $chartHeight = 82;
    $chartPadX = 24;
    $chartPadY = 10;
    $chartValues = $reportCurve->pluck('equity')->map(fn ($value) => (float) $value);
    $chartMin = $chartValues->isNotEmpty() ? (float) $chartValues->min() : 0.0;
    $chartMax = $chartValues->isNotEmpty() ? (float) $chartValues->max() : 1.0;
    $chartRange = max(1.0, $chartMax - $chartMin);
    $chartPointCount = max(1, $reportCurve->count() - 1);
    $chartPoints = $reportCurve->map(function ($point, $index) use ($chartWidth, $chartHeight, $chartPadX, $chartPadY, $chartMin, $chartRange, $chartPointCount) {
        $x = $chartPadX + (($chartWidth - (2 * $chartPadX)) * ($index / $chartPointCount));
        $y = $chartPadY + (($chartHeight - (2 * $chartPadY)) * (1 - (((float) $point['equity'] - $chartMin) / $chartRange)));
        return round($x, 2).','.round($y, 2);
    })->join(' ');
    $areaPoints = $chartPoints !== '' ? $chartPadX.','.($chartHeight - $chartPadY).' '.$chartPoints.' '.($chartWidth - $chartPadX).','.($chartHeight - $chartPadY) : '';
@endphp
<table class="overview"><tr><td width="31%" class="depot-card"><h2>Depotdaten</h2>
<div class="depot-row"><span>Depot</span><b>{{ $portfolio->name }}</b></div><div class="depot-row"><span>Startkapital</span><b>{{ number_format((float)$run->initial_capital,2,',','.') }} {{ $portfolio->currency }}</b></div><div class="depot-row"><span>Endkapital</span><b>{{ number_format((float)$run->final_capital,2,',','.') }} {{ $portfolio->currency }}</b></div><div class="depot-row"><span>Performance</span><b>{{ number_format((float)($summary['performance_percent']??0),2,',','.') }} %</b></div><div class="depot-row"><span>Max. Drawdown</span><b>{{ number_format((float)($summary['max_drawdown_percent']??0),2,',','.') }} %</b></div>
<div>@foreach($portfolio->strategies as $strategy)<span class="strategy">{{ $strategy->name }}</span>@endforeach</div></td><td width="69%" class="chart-card"><h2>Historische Depotentwicklung</h2>
@if($reportCurve->isNotEmpty())<svg width="100%" height="82" viewBox="0 0 {{ $chartWidth }} {{ $chartHeight }}" xmlns="http://www.w3.org/2000/svg"><line x1="{{ $chartPadX }}" y1="{{ $chartPadY }}" x2="{{ $chartPadX }}" y2="{{ $chartHeight-$chartPadY }}" stroke="#aab7be" stroke-width=".6"/><line x1="{{ $chartPadX }}" y1="{{ $chartHeight-$chartPadY }}" x2="{{ $chartWidth-$chartPadX }}" y2="{{ $chartHeight-$chartPadY }}" stroke="#aab7be" stroke-width=".6"/><polygon points="{{ $areaPoints }}" fill="#55bcb2" fill-opacity=".14"/><polyline points="{{ $chartPoints }}" fill="none" stroke="#168d88" stroke-width="1.7"/><text x="1" y="{{ $chartPadY+3 }}" font-size="6" fill="#64748b">{{ number_format($chartMax,0,',','.') }}</text><text x="1" y="{{ $chartHeight-$chartPadY }}" font-size="6" fill="#64748b">{{ number_format($chartMin,0,',','.') }}</text><text x="{{ $chartPadX }}" y="{{ $chartHeight-1 }}" font-size="6" fill="#64748b">{{ $reportCurve->first()['date'] }}</text><text x="{{ $chartWidth-$chartPadX }}" y="{{ $chartHeight-1 }}" font-size="6" text-anchor="end" fill="#64748b">{{ $reportCurve->last()['date'] }}</text></svg>@else<div class="muted">Keine Entwicklungskurve vorhanden.</div>@endif
</td></tr></table>
<table class="grid"><tr>
@foreach([['Startkapital',$run->initial_capital,' '.$portfolio->currency],['Endkapital',$run->final_capital,' '.$portfolio->currency],['Performance',$summary['performance_percent'] ?? 0,' %'],['Trades',$run->trades_count,''],['Trefferquote',$summary['hit_rate_percent'] ?? 0,' %'],['Profitfaktor',$summary['profit_factor'] ?? '—',''],['Max. Drawdown',$summary['max_drawdown_percent'] ?? 0,' %'],['Kosten',$summary['total_costs'] ?? 0,' '.$portfolio->currency]] as [$label,$value,$suffix])
<td width="12.5%"><div class="card"><b>{{ $label }}</b><div class="value">{{ is_numeric($value)?number_format((float)$value,$label==='Trades'?0:2,',','.'):$value }}{{ $suffix }}</div></div></td>
@endforeach
</tr></table>
<h2>Transaktionen</h2><table class="data"><thead><tr><th>Datum</th><th>Aktion</th><th>Aktie</th><th>Stück</th><th>Kurs</th><th>Gebühr</th><th>Strategien</th></tr></thead><tbody>
@foreach($transactions as $transaction)<tr><td>{{ $transaction->transaction_date?->format('d.m.Y') }}</td><td class="{{ $transaction->type==='sell'?'sell':'buy' }}">{{ strtoupper($transaction->type) }}</td><td>{{ $transaction->instrument?->symbol }}</td><td>{{ number_format($transaction->quantity,0,',','.') }}</td><td>{{ number_format($transaction->price,2,',','.') }}</td><td>{{ number_format($transaction->fees,2,',','.') }}</td><td>{{ collect(data_get($transaction->meta,'strategy_ids',[data_get($transaction->meta,'strategy_id')]))->filter()->join(', ') }}</td></tr>@endforeach
</tbody></table></body></html>
