<x-app-layout>
    <div class="mx-auto max-w-7xl px-3 py-5 text-[var(--ak-text)] sm:px-5 lg:py-8">
        <div class="mb-5 flex items-end justify-between gap-3"><div><p class="text-[10px] font-black uppercase tracking-[.2em] text-amber-400">{{ __('Versionierte Auswertungen') }}</p><h1 class="mt-1 text-3xl font-black">{{ __('Top-10 Ranking-Historie') }}</h1><p class="mt-1 text-sm text-[var(--ak-muted)]">{{ __('Rang, Kennzahlen und Kommentare bleiben je Lauf nachvollziehbar.') }}</p></div><a href="{{ route('screener.index') }}" class="inline-flex h-10 items-center rounded-xl border border-cyan-400/35 px-4 text-xs font-black text-cyan-300">{{ __('Zum Screener') }}</a></div>
        <div class="grid gap-5 lg:grid-cols-[.8fr_1.6fr]">
            <section class="rounded-2xl border border-cyan-400/25 bg-[var(--ak-card)] p-4 shadow-[var(--ak-shadow)]"><h2 class="mb-3 text-sm font-black uppercase tracking-widest text-cyan-300">{{ __('Läufe') }}</h2><div class="space-y-2">@forelse($runs as $run)<a href="{{ route('screener.history', ['run' => $run->id]) }}" class="block rounded-xl border p-3 {{ request('run') == $run->id ? 'border-cyan-300 bg-cyan-400/10' : 'border-[var(--ak-border)] bg-[var(--ak-surface-muted)]' }}"><div class="flex justify-between gap-2 text-sm font-black"><span>#{{ $run->id }} · {{ $run->item_count }} Aktien</span><span class="text-xs text-[var(--ak-muted)]">{{ CarbonCarbon::parse($run->generated_at)->format('d.m.Y H:i') }}</span></div><p class="mt-1 text-[11px] text-[var(--ak-muted)]">{{ $run->model ?: __('Deterministisches Ranking') }} · {{ $run->estimated_cost_usd !== null ? number_format((float) $run->estimated_cost_usd, 4, ',', '.').' USD' : __('ohne KI-Kommentar') }}</p></a>@empty<p class="text-sm text-[var(--ak-muted)]">{{ __('Noch keine Läufe vorhanden.') }}</p>@endforelse</div></section>
            <section class="overflow-hidden rounded-2xl border border-cyan-400/25 bg-[var(--ak-card)] shadow-[var(--ak-shadow)]"><div class="border-b border-[var(--ak-border)] px-4 py-4"><h2 class="text-sm font-black uppercase tracking-widest text-cyan-300">{{ __('Aktien und Begründungen') }}</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-[var(--ak-surface-muted)] text-[10px] uppercase tracking-wider text-[var(--ak-muted)]"><tr><th class="px-4 py-3">#</th><th class="px-4 py-3">{{ __('Aktie') }}</th><th class="px-4 py-3">{{ __('Score') }}</th><th class="px-4 py-3">{{ __('Begründung') }}</th></tr></thead><tbody>@forelse($selected as $item)<tr class="border-t border-[var(--ak-border)]"><td class="px-4 py-3 font-black text-amber-300">{{ $item->rank }}</td><td class="px-4 py-3"><strong>{{ $item->symbol }}</strong><span class="block text-xs text-[var(--ak-muted)]">{{ $item->name }}</span></td><td class="px-4 py-3 font-black">{{ number_format((float) $item->ranking_score, 1, ',', '.') }}</td><td class="max-w-xl px-4 py-3 text-xs leading-5 text-[var(--ak-muted)]">{{ app()->getLocale() === 'en' ? ($item->comment_en ?: $item->comment_de) : ($item->comment_de ?: $item->comment_en) }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-12 text-center text-sm text-[var(--ak-muted)]">{{ __('Wähle links einen Lauf aus.') }}</td></tr>@endforelse</tbody></table></div></section>
        </div>
    </div>
</x-app-layout>
