<x-app-layout>
@php
    $horizons = [10 => 'expected_return_10d', 20 => 'expected_return_20d', 40 => 'expected_return_40d'];
    $largestReturn = max(1, (float) collect($stocks)->flatMap(fn ($stock) => collect($horizons)->map(fn ($field) => is_numeric($stock->{$field} ?? null) ? abs((float)$stock->{$field}) : null)->filter())->max());
    $flag = fn (?string $country): string => preg_match('/^[A-Z]{2}$/', strtoupper((string)$country)) && function_exists('mb_chr')
        ? mb_chr(127397 + ord(strtoupper($country)[0])).mb_chr(127397 + ord(strtoupper($country)[1]))
        : '🌐';
@endphp
<main class="mx-auto max-w-[96rem] px-3 py-5 text-[var(--ak-text)] sm:px-5 lg:py-8">
    <header class="mb-3 flex flex-wrap items-center justify-between gap-3"><div><p class="text-[9px] font-black uppercase tracking-[.16em] text-cyan-400">{{ __('Service-Datenbank') }}</p><h1 class="text-3xl font-black tracking-tight">{{ __('Aktienscreener · Tabelle') }}</h1></div><a href="{{ route('screener.index', request()->query()) }}" class="inline-flex h-10 items-center rounded-xl border border-cyan-400/35 bg-cyan-400/[.08] px-4 text-xs font-black text-cyan-300">{{ __('Kartenansicht') }}</a></header>

    <section x-data="{open:false}" class="mb-4"><button type="button" @click="open=!open" class="flex h-10 w-full items-center justify-between rounded-xl border border-cyan-400/30 bg-[var(--ak-card)] px-4 text-xs font-black text-cyan-300"><span class="inline-flex items-center gap-2"><x-heroicon-o-adjustments-horizontal class="h-4 w-4"/>{{ __('Filter anzeigen') }}</span><x-heroicon-o-chevron-down class="h-4 w-4 transition" x-bind:class="open&&'rotate-180'"/></button>
        <form x-cloak x-show="open" method="GET" class="screener-filter-bar mt-2 flex flex-wrap gap-2 rounded-xl border border-cyan-400/25 bg-[var(--ak-card)] p-3 text-[17px]" style="font-size:17px">
            <input name="q" value="{{ request('q') }}" placeholder="{{ __('Aktie oder Symbol') }}" class="ak-input h-10 min-w-[210px] flex-1 text-sm">
            <select name="country" class="ak-input h-10 min-w-[150px] text-sm"><option value="">{{ __('Alle Länder') }}</option>@foreach($countries as $country)<option value="{{ $country }}" @selected(request('country')===$country)>{{ $country }}</option>@endforeach</select>
            <select name="sector" class="ak-input h-10 min-w-[170px] text-sm"><option value="">{{ __('Alle Sektoren') }}</option>@foreach($sectors as $sector)<option value="{{ $sector }}" @selected(request('sector')===$sector)>{{ $sector }}</option>@endforeach</select>
            @php $selectedRiskProfiles=collect(request('risk_class',[]));$defaultRiskProfiles=!request()->boolean('risk_profiles'); @endphp
            <fieldset class="screener-risk-choice"><legend class="sr-only">{{ __('Profil') }}</legend><input type="hidden" name="risk_profiles" value="1"><button type="button" onclick="this.closest('fieldset').querySelectorAll('input[type=checkbox]').forEach(input=>input.checked=true);this.form.requestSubmit()"><span>{{ __('Alle') }}</span></button>@foreach(['defensive'=>__('Defensiv'),'balanced'=>__('Ausgewogen'),'offensive'=>__('Offensiv')] as $value=>$label)<label><input type="checkbox" name="risk_class[]" value="{{ $value }}" @checked($defaultRiskProfiles||$selectedRiskProfiles->contains($value)) onchange="this.form.requestSubmit()"><span>{{ $label }}</span></label>@endforeach</fieldset>
            <select name="signal" class="ak-input h-10 min-w-[140px] text-sm"><option value="">{{ __('Alle Signale') }}</option>@foreach(['BUY','WATCH'] as $signal)<option value="{{ $signal }}" @selected(request('signal')===$signal)>{{ $signal }}</option>@endforeach</select>
            <select name="min_max_return" class="ak-input h-10 min-w-[185px] text-base font-bold" aria-label="{{ __('Maximale Rendite') }}">
                <option value="">{{ __('Max. Rendite') }} · {{ __('Alle') }}</option>
                @foreach(range(0,10,2) as $minimum)<option value="{{ $minimum }}" @selected((string)request('min_max_return')===(string)$minimum)>{{ __('Max. Rendite') }} ≥ {{ $minimum > 0 ? '+' : '' }}{{ $minimum }} %</option>@endforeach
            </select>
            <select name="limit" class="ak-input h-10 min-w-[110px] text-sm">@foreach(['10'=>'Top 10','25'=>'Top 25','50'=>'Top 50','100'=>'Top 100','all'=>__('Alle')] as $value=>$label)<option value="{{ $value }}" @selected((string)request('limit','10')===(string)$value)>{{ $label }}</option>@endforeach</select>
            <button class="h-10 rounded-lg bg-cyan-400 px-4 text-xs font-black text-slate-950">{{ __('Suchen') }}</button><a href="{{ route('screener.table') }}" class="inline-flex h-10 items-center rounded-lg border border-amber-400/35 px-4 text-xs font-black text-amber-300">{{ __('Reset') }}</a>
        </form>
    </section>

    <section class="ak-card ak-card-static ak-dashboard-card overflow-hidden p-0">
        <header class="flex items-center justify-between border-b border-cyan-400/15 px-4 py-3"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl border border-cyan-400/30 bg-cyan-400/[.08] text-cyan-300"><x-heroicon-o-chart-bar class="h-5 w-5"/></span><div><p class="text-[9px] font-black uppercase tracking-[.16em] text-cyan-400">{{ __('Aktien-Ranking') }}</p><h2 class="text-base font-black">{{ __('Ausblick und Risiko') }}</h2></div></div><span class="text-[9px] font-bold text-[var(--ak-muted)]">{{ count($stocks) }} {{ __('Aktien') }}</span></header>
        <div class="overflow-x-auto"><div id="stock-matrix" class="min-w-[900px]">
            <div class="stock-matrix-row stock-matrix-head"><span><button type="button" data-stock-sort="name">{{ __('Aktie') }} <i>↕</i></button></span><span><button type="button" data-stock-sort="ranking">{{ __('Signal') }} <i>↕</i></button></span><span><button type="button" data-stock-sort="risk">{{ __('Risiko') }} <i>↕</i></button></span><span class="stock-horizons">@foreach(array_keys($horizons) as $days)<i><button type="button" data-stock-sort="return_{{ $days }}">{{ $days }}T <em>↕</em></button></i>@endforeach</span></div>
            @forelse($stocks as $stock)
                <div x-data="{expanded:false}" class="stock-matrix-item" data-stock-row data-sort-name="{{ mb_strtolower($stock->name.' '.$stock->symbol) }}" data-sort-ranking="{{ is_numeric($stock->ranking_score) ? $stock->ranking_score : '' }}" data-sort-return_10="{{ is_numeric($stock->expected_return_10d) ? $stock->expected_return_10d : '' }}" data-sort-return_20="{{ is_numeric($stock->expected_return_20d) ? $stock->expected_return_20d : '' }}" data-sort-return_40="{{ is_numeric($stock->expected_return_40d) ? $stock->expected_return_40d : '' }}" data-sort-risk="{{ is_numeric($stock->risk_percent) ? $stock->risk_percent : '' }}">
                <button type="button" @click="expanded=!expanded;if(expanded)$nextTick(()=>window.loadStockMatrixChart($refs.chart))" :aria-expanded="expanded" class="stock-matrix-row w-full text-left">
                    <span class="stock-matrix-name"><i>{{ $flag($stock->country) }}</i><span><b>#{{ $stock->screening_rank }} · {{ $stock->name }}</b><small><em>{{ $stock->symbol }}</em><strong class="stock-signal-badge" data-signal="{{ strtolower($stock->personalized_signal) }}">{{ $stock->personalized_signal }}</strong></small></span><x-heroicon-o-chevron-down class="ml-auto h-4 w-4 shrink-0 text-cyan-300 transition" x-bind:class="expanded&&'rotate-180'"/></span>
                    @php
                        $ranking = is_numeric($stock->ranking_score ?? null) ? max(0, min(100, (float)$stock->ranking_score)) : null;
                        $risk = is_numeric($stock->risk_percent ?? null) ? max(0, min(100, (float)$stock->risk_percent)) : null;
                        $rankingColor = $ranking === null ? '#64748b' : ($ranking >= 75 ? '#34d399' : ($ranking >= 50 ? '#fbbf24' : '#fb7185'));
                        $riskColor = $risk === null ? '#64748b' : ($risk <= 30 ? '#34d399' : ($risk <= 60 ? '#fbbf24' : '#fb7185'));
                    @endphp
                    <span class="stock-donut-cell"><i class="screener-metric-donut" style="--donut-value:{{ $ranking ?? 0 }}%;--donut-color:{{ $rankingColor }}"><span>{{ $stock->serving_buy_rating ?: '—' }}</span></i></span>
                    <span class="stock-donut-cell"><i class="screener-metric-donut" style="--donut-value:{{ $risk ?? 0 }}%;--donut-color:{{ $riskColor }}"><span>{{ \App\Support\QualityGrade::riskLevel($risk) ?? '—' }}</span></i></span>
                    <span class="stock-horizons">@foreach($horizons as $days=>$field)@php $value=is_numeric($stock->{$field}??null)?(float)$stock->{$field}:null;$width=$value===null?0:min(44,abs($value)/$largestReturn*44); @endphp
                    <i class="stock-matrix-cell"><small>{{ $days }}T</small><i class="axis"></i>@if($value!==null)<i class="bar {{ $value>=0?'positive':'negative' }}" style="width:{{ $width }}%"></i>@endif<b class="{{ $value===null?'':($value>=0?'text-emerald-400':'text-rose-400') }}">{{ $value===null?'—':(($value>0?'+':'').number_format($value,1,',','.').' %') }}</b></i>@endforeach</span>
                </button>
                <div x-cloak x-show="expanded" x-collapse class="stock-matrix-details">
                    @php
                        $description = app()->getLocale()==='en'
                            ? (data_get($stock, 'business_summary_en') ?: data_get($stock, 'business_description_en') ?: data_get($stock, 'business_summary') ?: data_get($stock, 'business_description'))
                            : (data_get($stock, 'business_summary') ?: data_get($stock, 'business_description') ?: data_get($stock, 'business_summary_en') ?: data_get($stock, 'business_description_en'));
                        $opportunities = collect($stock->assessment_pros ?? [])->filter()->take(3);
                        $risks = collect($stock->assessment_cons ?? [])->filter()->take(3);
                    @endphp
                    <div class="stock-matrix-expanded-grid">
                        <div x-ref="chart" data-chart-url="{{ route('screener.chart', ['instrument'=>$stock->instrument_id]) }}" class="stock-matrix-chart"><div class="flex h-24 items-center justify-center text-[9px] font-bold text-[var(--ak-muted)]">{{ __('Prognosechart wird geladen …') }}</div></div>
                        <section class="stock-matrix-description"><h3>{{ __('Unternehmen') }}</h3><p>{{ $description ?: __('Eine Unternehmensbeschreibung ist derzeit nicht verfügbar.') }}</p></section>
                        <section class="stock-matrix-opportunities"><div><h3>{{ __('Chancen') }}</h3>@forelse($opportunities as $item)<p><i>+</i>{{ $item }}</p>@empty<p class="is-empty">{{ __('Keine zusätzlichen Chancen ausgewiesen.') }}</p>@endforelse</div><div><h3>{{ __('Risiken') }}</h3>@forelse($risks as $item)<p><i>−</i>{{ $item }}</p>@empty<p class="is-empty">{{ __('Keine zusätzlichen Risiken ausgewiesen.') }}</p>@endforelse</div></section>
                    </div>
                    <section class="stock-model-trigger">
                        <header><x-heroicon-o-cpu-chip class="h-4 w-4" /><div><small>{{ __('Auslösendes Modell') }}</small><strong>{{ $stock->trigger_model_name ?: '—' }}</strong></div></header>
                        <dl>
                            <div><dt>{{ __('Horizont') }}</dt><dd>{{ $stock->trigger_model_horizon ? $stock->trigger_model_horizon.'T' : '—' }}</dd></div>
                            <div><dt>{{ __('Globales Ranking') }}</dt><dd>{{ $stock->screening_rank ? '#'.$stock->screening_rank : '—' }}</dd></div>
                            <div><dt>{{ __('Sektorrang') }}</dt><dd>{{ $stock->sector_rank ? '#'.$stock->sector_rank : '—' }}</dd></div>
                            <div><dt>{{ __('Modellqualität') }}</dt><dd>{{ $stock->model_quality_tier_name ?: '—' }}</dd></div>
                            <div><dt>{{ __('Quality Gate') }}</dt><dd class="{{ $stock->trigger_model_quality_gate_passed ? 'text-emerald-400' : 'text-rose-400' }}">{{ $stock->trigger_model_quality_gate_passed ? __('Bestanden') : __('Nicht bestanden') }}</dd></div>
                            <div title="{{ $stock->trigger_model_release_id }}"><dt>{{ __('Release') }}</dt><dd>{{ $stock->trigger_model_release_id ? \Illuminate\Support\Str::limit($stock->trigger_model_release_id, 8, '') : '—' }}</dd></div>
                        </dl>
                    </section>
                    <div class="stock-matrix-detail-meta">
                    <dl>
                        <div><dt>{{ __('Signal') }}</dt><dd>{{ $stock->personalized_signal }}</dd></div>
                        <div><dt>{{ __('KI-Bewertung') }}</dt><dd>{{ $stock->serving_buy_rating ?: '—' }}</dd></div>
                        <div><dt>{{ __('Konfidenz') }}</dt><dd>{{ is_numeric($stock->confidence_percent) ? number_format($stock->confidence_percent, 0, ',', '.').' %' : '—' }}</dd></div>
                        <div><dt>{{ __('Hit-Rate') }}</dt><dd>{{ is_numeric($stock->ranking_hit_rate) ? number_format($stock->ranking_hit_rate, 1, ',', '.').' %' : '—' }}</dd></div>
                        <div><dt>{{ __('Profitfaktor') }}</dt><dd>{{ is_numeric($stock->ranking_profit_factor) ? number_format($stock->ranking_profit_factor, 2, ',', '.') : '—' }}</dd></div>
                        <div><dt>{{ __('Drawdown') }}</dt><dd>{{ is_numeric($stock->ranking_drawdown) ? number_format($stock->ranking_drawdown, 1, ',', '.').' %' : '—' }}</dd></div>
                    </dl>
                    <a href="{{ route('stocks.show', ['symbol'=>$stock->symbol, 'return_to'=>request()->getRequestUri()]) }}">{{ __('Aktiendetails') }} <span>→</span></a>
                    </div>
                </div>
                </div>
            @empty<div class="p-10 text-center text-sm text-[var(--ak-muted)]">{{ __('Keine Aktien für diese Auswahl gefunden.') }}</div>@endforelse
        </div></div>
    </section>
</main>
<style>
.stock-model-trigger{display:flex;align-items:center;gap:.7rem;margin-top:.55rem;padding:.55rem .65rem;border:1px solid rgba(34,211,238,.16);border-radius:.7rem;background:rgba(34,211,238,.035)}.stock-model-trigger>header{display:flex;min-width:190px;align-items:center;gap:.55rem;color:#22d3ee}.stock-model-trigger>header div{display:flex;min-width:0;flex-direction:column}.stock-model-trigger>header small{font-size:7px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.stock-model-trigger>header strong{overflow:hidden;margin-top:.12rem;text-overflow:ellipsis;white-space:nowrap;font-size:10px;color:var(--ak-text)}.stock-model-trigger>dl{display:grid!important;flex:1;grid-template-columns:repeat(6,minmax(70px,1fr))!important;gap:.35rem!important}.stock-model-trigger>dl div{padding:.35rem .45rem!important}.stock-model-trigger>dl dt{font-size:6px!important}.stock-model-trigger>dl dd{font-size:9px!important}@media(max-width:640px){.stock-model-trigger{align-items:stretch;flex-direction:column}.stock-model-trigger>header{min-width:0}.stock-model-trigger>dl{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
.stock-matrix-row{display:grid;grid-template-columns:minmax(270px,1.55fr) 90px 90px minmax(435px,3fr);border-top:1px solid color-mix(in srgb,var(--ak-muted) 14%,transparent)}.stock-matrix-head{border-top:0;background:color-mix(in srgb,var(--ak-card) 82%,var(--ak-bg) 18%);font-size:8px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:var(--ak-muted)}.stock-matrix-row>span{display:flex;min-width:0;align-items:center;padding:.65rem .75rem;border-left:1px solid color-mix(in srgb,var(--ak-muted) 12%,transparent)}.stock-matrix-row>span:first-child{border-left:0}.stock-matrix-row:not(.stock-matrix-head):hover{background:rgba(34,211,238,.04)}.stock-matrix-name{gap:.65rem}.stock-matrix-name>i{font-size:1.05rem;font-style:normal}.stock-matrix-name span{display:flex;min-width:0;flex-direction:column}.stock-matrix-name b{overflow:hidden;font-size:10px;text-overflow:ellipsis;white-space:nowrap}.stock-matrix-name small{font-size:7px;color:var(--ak-muted)}.stock-horizons{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));padding:0!important}.stock-horizons>i{display:flex;min-width:0;min-height:3.35rem;align-items:center;justify-content:center;border-left:1px solid color-mix(in srgb,var(--ak-muted) 12%,transparent);font-style:normal}.stock-horizons>i:first-child{border-left:0}.stock-matrix-cell{position:relative;justify-content:center;overflow:hidden}.stock-matrix-cell>small{display:none}.stock-matrix-cell>b{position:relative;z-index:3;padding:2px 5px;border-radius:5px;background:color-mix(in srgb,var(--ak-card) 78%,transparent);font-size:9px;font-weight:900}.stock-matrix-cell .axis{position:absolute;top:20%;bottom:20%;left:50%;width:1px;background:color-mix(in srgb,var(--ak-muted) 32%,transparent)}.stock-matrix-cell .bar{position:absolute;top:30%;bottom:30%;min-width:2px}.stock-matrix-cell .positive{left:50%;background:linear-gradient(90deg,rgba(16,185,129,.25),rgba(16,185,129,.75));border-radius:0 5px 5px 0}.stock-matrix-cell .negative{right:50%;background:linear-gradient(270deg,rgba(244,63,94,.25),rgba(244,63,94,.75));border-radius:5px 0 0 5px}.stock-risk-cell{gap:.55rem}.stock-risk-cell>i{height:7px;flex:1;overflow:hidden;border-radius:999px;background:rgba(100,116,139,.18)}.stock-risk-cell em{display:block;height:100%;background:linear-gradient(90deg,#34d399,#fbbf24 55%,#fb7185);border-radius:inherit}.stock-risk-cell b{min-width:35px;text-align:right;font-size:9px}
.stock-matrix-details{padding:.65rem .8rem .75rem;border-top:1px dashed color-mix(in srgb,var(--ak-muted) 15%,transparent);background:color-mix(in srgb,var(--ak-card) 86%,#22d3ee 2%)}.stock-matrix-expanded-grid{display:grid;grid-template-columns:1.3fr 1fr 1.15fr;gap:.55rem}.stock-matrix-chart,.stock-matrix-description,.stock-matrix-opportunities{min-width:0;padding:.45rem .65rem;border:1px solid color-mix(in srgb,var(--ak-muted) 14%,transparent);border-radius:.7rem;background:color-mix(in srgb,var(--ak-card) 92%,transparent)}.stock-matrix-description h3,.stock-matrix-opportunities h3{font-size:7px;font-weight:900;letter-spacing:.1em;text-transform:uppercase;color:#22d3ee}.stock-matrix-description p{display:-webkit-box;overflow:hidden;margin-top:.4rem;font-size:8px;line-height:1.5;color:var(--ak-muted);-webkit-box-orient:vertical;-webkit-line-clamp:7}.stock-matrix-opportunities{display:grid;grid-template-columns:1fr 1fr;gap:.55rem}.stock-matrix-opportunities>div+div{padding-left:.55rem;border-left:1px solid color-mix(in srgb,var(--ak-muted) 14%,transparent)}.stock-matrix-opportunities p{display:flex;gap:.3rem;margin-top:.32rem;font-size:7px;line-height:1.4;color:var(--ak-muted)}.stock-matrix-opportunities p i{flex:none;font-style:normal;font-weight:900;color:#34d399}.stock-matrix-opportunities>div+div p i{color:#fb7185}.stock-matrix-opportunities p.is-empty{font-style:italic}.stock-matrix-detail-meta{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-top:.55rem}.stock-matrix-details dl{display:grid;flex:1;grid-template-columns:repeat(6,minmax(80px,1fr));gap:.5rem}.stock-matrix-details dl div{padding:.45rem .55rem;border:1px solid color-mix(in srgb,var(--ak-muted) 14%,transparent);border-radius:.55rem}.stock-matrix-details dt{font-size:7px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:var(--ak-muted)}.stock-matrix-details dd{margin-top:.15rem;font-size:10px;font-weight:900}.stock-matrix-detail-meta>a{flex:none;padding:.55rem .75rem;border:1px solid rgba(34,211,238,.28);border-radius:.6rem;font-size:9px;font-weight:900;color:#22d3ee}@media(max-width:900px){.stock-matrix-expanded-grid{grid-template-columns:1fr}.stock-matrix-detail-meta{align-items:stretch;flex-direction:column}.stock-matrix-details dl{grid-template-columns:repeat(3,1fr)}.stock-matrix-detail-meta>a{align-self:flex-end}}
.stock-matrix-head button{display:inline-flex;width:100%;align-items:center;justify-content:center;gap:.35rem;font:inherit;letter-spacing:inherit;text-transform:inherit;color:inherit}.stock-matrix-head>span:first-child button{justify-content:flex-start}.stock-matrix-head button i{font-style:normal;color:#22d3ee;opacity:.65}.stock-matrix-head button.is-active{color:#22d3ee}.stock-matrix-head button.is-active i{opacity:1}
.stock-donut-cell{justify-content:center}.stock-donut-cell .screener-metric-donut{width:2.75rem;height:2.75rem}.stock-donut-cell .screener-metric-donut::after{inset:3px;background:var(--ak-workspace-card-hover)!important}.stock-donut-cell .screener-metric-donut span{font-size:.72rem;font-style:normal}.stock-mobile-slider{display:none}
.stock-matrix-name small{display:flex!important;align-items:center;gap:.35rem;margin-top:.28rem}.stock-matrix-name small em{overflow:hidden;text-overflow:ellipsis;font-style:normal}.stock-signal-badge{display:inline-flex;min-width:2.6rem;flex:none;align-items:center;justify-content:center;border:1px solid rgba(148,163,184,.2);border-radius:.3rem;padding:.08rem .25rem;font-size:6px!important;line-height:1.15;letter-spacing:.06em;text-align:center}.stock-signal-badge[data-signal="buy"]{border-color:rgba(52,211,153,.38);background:rgba(52,211,153,.12);color:#34d399}.stock-signal-badge[data-signal="watch"]{border-color:rgba(163,230,53,.36);background:rgba(163,230,53,.10);color:#a3e635}
@media(max-width:640px){main:has(#stock-matrix){padding:.65rem .35rem}main:has(#stock-matrix)>header{margin-bottom:.5rem;padding-inline:.25rem}main:has(#stock-matrix)>header h1{font-size:1.35rem}main:has(#stock-matrix)>header>a{height:2rem;padding-inline:.65rem;font-size:.65rem}main:has(#stock-matrix)>section{margin-bottom:.55rem}.ak-dashboard-card:has(#stock-matrix)>div{overflow-x:hidden}#stock-matrix{min-width:0;width:100%}.stock-matrix-row{grid-template-columns:minmax(0,43%) 13% 13% minmax(0,31%)}.stock-matrix-row>span{padding:.38rem .28rem}.stock-matrix-head{font-size:7px}.stock-matrix-head>span{justify-content:center}.stock-matrix-head>span:first-child{justify-content:flex-start}.stock-matrix-head button{gap:.1rem}.stock-matrix-head>.stock-horizons{grid-column:4;grid-row:1;grid-template-columns:1fr}.stock-matrix-head>.stock-horizons>i{display:none;min-height:1.4rem}.stock-matrix-head>.stock-horizons>i:first-child{display:flex}.stock-matrix-head>.stock-horizons>i:first-child button{font-size:0}.stock-matrix-head>.stock-horizons>i:first-child button::before{content:'{{ __('Ausblick') }}';font-size:7px}.stock-matrix-head>.stock-horizons em{font-style:normal;color:#22d3ee}.stock-matrix-name{gap:.32rem}.stock-matrix-name>i{font-size:.9rem}.stock-matrix-name b{font-size:10px;line-height:1.22;white-space:normal}.stock-matrix-name small{font-size:7px}.stock-matrix-name svg{width:.8rem;height:.8rem}.stock-donut-cell{display:flex!important;padding:.2rem!important}.stock-donut-cell .screener-metric-donut{width:2rem;height:2rem}.stock-donut-cell .screener-metric-donut::after{inset:2px}.stock-donut-cell .screener-metric-donut span{font-size:.58rem}.stock-horizons{grid-column:4;grid-row:1;grid-template-columns:1fr}.stock-horizons>i{min-height:1.35rem;border-left:0;border-top:1px solid color-mix(in srgb,var(--ak-muted) 10%,transparent)}.stock-horizons>i:first-child{border-top:0}.stock-matrix-cell>small{display:block;position:absolute;left:.18rem;z-index:4;font-size:6px;font-style:normal;font-weight:900;color:var(--ak-muted)}.stock-matrix-cell>b{padding:1px 3px;font-size:8px}.stock-matrix-cell .axis{top:14%;bottom:14%}.stock-matrix-cell .bar{top:28%;bottom:28%}.stock-matrix-details{grid-column:1/-1;gap:.45rem;padding:.45rem}.stock-matrix-details dl{grid-template-columns:repeat(2,1fr);gap:.3rem}.stock-matrix-details dl div{padding:.35rem}.stock-matrix-details dt{font-size:7px}.stock-matrix-details dd{font-size:9px}.stock-matrix-detail-meta>a{align-self:flex-end;padding:.45rem .6rem;font-size:8px}.ak-dashboard-card:has(#stock-matrix)>header{padding:.65rem}.ak-dashboard-card:has(#stock-matrix)>header>div>span{width:2.1rem;height:2.1rem}.ak-dashboard-card:has(#stock-matrix)>header h2{font-size:.9rem}}
@media(max-width:640px){.stock-matrix-row{grid-template-columns:minmax(0,40%) 15% 15% minmax(0,30%)}.stock-donut-cell .screener-metric-donut{display:grid}}
.stock-matrix-chart,.stock-matrix-description,.stock-matrix-opportunities{padding:.6rem .75rem}.stock-matrix-chart svg{height:9rem}.stock-matrix-chart>div>div:first-child{font-size:10px}.stock-matrix-description h3,.stock-matrix-opportunities h3{font-size:9px}.stock-matrix-description p{margin-top:.5rem;font-size:11px;line-height:1.55}.stock-matrix-opportunities{gap:.65rem}.stock-matrix-opportunities>div+div{padding-left:.65rem}.stock-matrix-opportunities p{gap:.35rem;margin-top:.42rem;font-size:10px;line-height:1.45}
</style>
<script>
document.addEventListener('DOMContentLoaded',()=>{
    const matrix=document.querySelector('#stock-matrix');if(!matrix)return;
    const head=matrix.querySelector('.stock-matrix-head');let active=null,direction='desc';
    matrix.querySelectorAll('[data-stock-sort]').forEach(button=>button.addEventListener('click',()=>{
        const key=button.dataset.stockSort;direction=active===key&&direction==='desc'?'asc':'desc';active=key;
        matrix.querySelectorAll('[data-stock-sort]').forEach(item=>{item.classList.toggle('is-active',item===button);const indicator=item.querySelector('i,em');if(indicator)indicator.textContent=item===button?(direction==='asc'?'↑':'↓'):'↕'});
        const rows=[...matrix.querySelectorAll('[data-stock-row]')];
        rows.sort((left,right)=>{const a=left.getAttribute(`data-sort-${key}`)??'';const b=right.getAttribute(`data-sort-${key}`)??'';if(a===''&&b==='')return 0;if(a==='')return 1;if(b==='')return-1;const comparison=key==='name'?a.localeCompare(b,document.documentElement.lang||'de'):(Number(a)-Number(b));return direction==='asc'?comparison:-comparison});
        rows.forEach(row=>matrix.appendChild(row));matrix.prepend(head);
    }));
});
window.loadStockMatrixChart=async element=>{if(!element||element.dataset.chartState)return;element.dataset.chartState='loading';try{const response=await fetch(element.dataset.chartUrl,{credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);element.innerHTML=await response.text();element.dataset.chartState='loaded'}catch(error){element.dataset.chartState='failed';element.innerHTML='<div class="flex h-24 items-center justify-center px-4 text-center text-xs italic text-[var(--ak-muted)]">{{ __('Der Kurschart ist momentan nicht verfügbar.') }}</div>'}};
</script>
</x-app-layout>
